KNOWN_PEOPLE = {
    "actors": [
        "Leonardo DiCaprio", "Scarlett Johansson", "Robert Downey Jr", "Dwayne Johnson",
        "Tom Cruise", "Keanu Reeves", "Margot Robbie", "Denzel Washington", 
        "Emma Stone", "Brad Pitt", "Chris Hemsworth", "Chris Evans", 
        "Zendaya", "Gal Gadot", "Ryan Reynolds", "Jennifer Lawrence",
        "Hugh Jackman", "Johnny Depp", "Anne Hathaway", "Will Smith",
        "Joaquin Phoenix", "Christian Bale", "Tom Hardy", "Matt Damon",
        "Natalie Portman", "Cate Blanchett", "Sandra Bullock", "Meryl Streep",
        "Nicole Kidman", "Viola Davis", "Florence Pugh", "Tilda Swinton",
        "Adam Driver", "Timothée Chalamet", "Jake Gyllenhaal", "Mark Ruffalo",
        "Chadwick Boseman", "Paul Rudd", "Chris Pratt", "Eddie Redmayne",
        "Rami Malek", "Daniel Craig", "Pierce Brosnan", "Sean Connery",
        "Idris Elba", "Cillian Murphy", "Michael Fassbender", "Ben Affleck",
        "Amy Adams", "Emily Blunt", "Emma Watson", "Lupita Nyong'o",
        "Jessica Chastain", "Kristen Stewart", "Robert Pattinson", "Andrew Garfield",
        "Zendaya", "Jared Leto", "Millie Bobby Brown", "Anya Taylor-Joy",
        "Saoirse Ronan", "Benedict Cumberbatch", "Tom Holland", "Harrison Ford",
        "Angelina Jolie", "Julia Roberts", "Bruce Willis", "Sylvester Stallone",
        "Morgan Freeman", "Steve Carell", "Chris Pine", "Jamie Foxx",
        "Jason Momoa", "Henry Cavill", "Ezra Miller", "Gal Gadot",
        "Anne Hathaway", "Reese Witherspoon", "Penélope Cruz", "Salma Hayek",
        "Zoe Saldana", "Winona Ryder", "Helena Bonham Carter", "Samuel L. Jackson",
        "Michael B. Jordan", "Oscar Isaac", "Anthony Mackie", "Tessa Thompson",
        "Awkwafina", "Rachel McAdams", "Joseph Gordon-Levitt", "Ewan McGregor",
        "Shia LaBeouf", "Halle Berry", "Tom Hanks", "Robin Williams",
        "Heath Ledger", "Philip Seymour Hoffman", "Javier Bardem", "J.K. Simmons",
        "Mahershala Ali", "Forest Whitaker", "Bryan Cranston", "John Boyega","Danny DeVito",

        #Turkish actors
        "Kıvanç Tatlıtuğ", "Kenan İmirzalıoğlu", "Haluk Bilginer", "Engin Akyürek",
        "Burak Özçivit", "Çağatay Ulusoy", "Beren Saat", "Tuba Büyüküstün",
        "Meryem Uzerli", "Bergüzar Korel", "Cansu Dere", "Şener Şen",
        "Yılmaz Erdoğan", "Cem Yılmaz", "Erdal Beşikçioğlu", "Halit Ergenç",
        "Nejat İşler", "Fahriye Evcen", "Demet Evgar", "Murat Yıldırım",
        "Belçim Bilgin", "Melisa Sözen", "Okan Yalabık", "Ekin Koç"
    ],
    "directors": [
        "Steven Spielberg", "Christopher Nolan", "Quentin Tarantino", "Stanley Kubrick",
        "Martin Scorsese", "James Cameron", "Ridley Scott", "Tim Burton",
        "Peter Jackson", "Alfred Hitchcock", "Guillermo del Toro", "David Fincher",
        "Wes Anderson", "Sofia Coppola", "Spike Lee", "Francis Ford Coppola",
        "George Lucas", "Denis Villeneuve", "Greta Gerwig", "Jane Campion",
        "Taika Waititi", "Damien Chazelle", "Patty Jenkins", "Kathryn Bigelow",
        "Ang Lee", "Sam Mendes", "Luca Guadagnino", "Bong Joon Ho",
        "Yorgos Lanthimos", "Jordan Peele", "Robert Eggers", "Rian Johnson",
        "Jean-Pierre Jeunet", "Ken Loach", "Danny Boyle", "Alejandro González Iñárritu",
        "Paul Thomas Anderson", "Joel Coen", "Ethan Coen", "Baz Luhrmann",
        "Michael Bay", "Zack Snyder", "J.J. Abrams", "David Lynch",
        "Sergio Leone", "John Carpenter", "Clint Eastwood", "Mel Brooks",
        "Akira Kurosawa", "Hayao Miyazaki","Ari Aster", "Lana Wachowski",
        "Lilly Wachowski", "Chloé Zhao", 
        "James Wan", "Jon Favreau", "Peyton Reed", "Anthony Russo", 
        "Joe Russo", "Makoto Shinkai", "Park Chan-wook", "Hirokazu Kore-eda", 
        "Taika Waititi", "Matt Reeves", "Guillaume Canet", "Fernando Meirelles", 
        "Justin Lin", "M. Night Shyamalan", "Patrice Leconte", "Ang Lee",

        #Turkish directors
        "Nuri Bilge Ceylan", "Yılmaz Erdoğan", "Zeki Demirkubuz", "Ferzan Özpetek",
        "Fatih Akın", "Çağan Irmak", "Seren Yüce", "Reha Erdem",
        "Emin Alper", "Tayfun Pirselimoğlu", "Onur Ünlü", "Yeşim Ustaoğlu",
        "Mustafa Altıoklar", "Ömer Faruk Sorak", "Mert Baykal", "Yavuz Turgul",
        "Özgür Bakar", "Ali Atay", "Gani Müjde"
    ]
}
